### PR TITLE
About

### PR DESCRIPTION
**Pull request by Jay-cey**
For some reason, I can't get the local font to work...

### CODE REVIEW

**Comment by TressOhi** [comment]
> For some reason, I can't get the local font to work...

I'll check

**Comment by TressOhi** [comment]
The font loads properly on my end

**Comment by Jay-cey** [comment]
> The font loads properly on my end

I mean the custom font; that's only used once. Check line 10 in page.jsx file and the corresponding style in globals.css

**Comment by TressOhi** [comment]
'Zapfino'? It loads properly here. Check the image below.

image

**Comment by Jay-cey** [comment]
Alright, I'll check why it's not working on my side and make the necessary adjustments

**Pull request merged**
